name: Houz Hatz Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: sbp_f83289088213116c0a32a94ba8e3f4e5f41b9012
      SUPABASE_DB_PASSWORD: lm8989LM8989
      SUPABASE_PROJECT_ID: womqqsyjlbrqasiozyix

    steps:
      # Step 1: Checkout your repo
      - uses: actions/checkout@v3

      # Step 2: Install Supabase CLI
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      # Step 3: Link to your Supabase project
      - name: Link Supabase project
        run: supabase link --project-ref $SUPABASE_PROJECT_ID

      # Step 4: Push any database updates
      - name: Push database changes
        run: supabase db push

      # Step 5: Deploy your Edge Function (frontend)
      - name: Deploy Edge Function (web)
        run: supabase functions deploy web --project-ref $SUPABASE_PROJECT_ID

      # Step 6: Post-deploy check (confirm live site)
      - name: Verify live site
        run: |
          echo "Checking live site status..."
          curl -I https://womqqsyjlbrqasiozyix.functions.supabase.co/web || exit 1
