name: Supabase Deploy

on:
  push:
    branches:
      - main  # runs when you push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: cli_r_cain@Lucas_1759260204
      SUPABASE_DB_PASSWORD: lm8989LM8989
      SUPABASE_PROJECT_ID: womqqsyjlbrqasiozyix

    steps:
      - uses: actions/checkout@v3

      - name: Set up Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link Supabase project
        run: supabase link --project-ref womqqsyjlbrqasiozyix

      - name: Push database changes
        run: supabase db push
